# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'satuanfull.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector as mc
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_FormSatuan(object):
    def setupUi(self, FormSatuan):
        FormSatuan.setObjectName("FormSatuan")
        FormSatuan.resize(566, 505)
        self.verticalLayoutWidget = QtWidgets.QWidget(FormSatuan)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(FormSatuan)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 10, 281, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_id = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout_2.addWidget(self.lineEdit_id)
        self.lineEdit_nama = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.verticalLayout_2.addWidget(self.lineEdit_nama)
        self.lineEdit_diskripsi = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_diskripsi.setObjectName("lineEdit_diskripsi")
        self.verticalLayout_2.addWidget(self.lineEdit_diskripsi)
        self.horizontalLayoutWidget = QtWidgets.QWidget(FormSatuan)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 461, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        self.pushButton.clicked.connect(self.insertSatuan)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        self.pushButton_2.clicked.connect(self.updateSatuan)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        self.pushButton_3.clicked.connect(self.deleteSatuan)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        self.pushButton_4.clicked.connect(self.loadSatuan)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.label_3 = QtWidgets.QLabel(FormSatuan)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(FormSatuan)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 230, 461, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.cellClicked.connect(self.cellClick)

        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(FormSatuan)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 461, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_3.textChanged.connect(self.cariData)
        
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)

        self.pushButton_5.clicked.connect(self.cariData)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)

        self.retranslateUi(FormSatuan)
        QtCore.QMetaObject.connectSlotsByName(FormSatuan)

    def cellClick(self, row, column):
        try:
            id = self.tableWidget.item(row, 0).text()
            name = self.tableWidget.item(row, 1).text()
            diskripsi = self.tableWidget.item(row, 2).text()
            self.lineEdit_id.setText(id)
            self.lineEdit_nama.setText(name)
            self.lineEdit_diskripsi.setText(diskripsi)
        except Exception as e:
            error_message = f"Error: {e}"
            self.label_3.setText(error_message)

    def insertSatuan(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "penjualan"
            )
            cursor = mydb.cursor()
            id = self.lineEdit_id.text()
            name = self.lineEdit_nama.text()
            diskripsi = self.lineEdit_diskripsi.text()

            sql = "INSERT INTO satuan (id, name, diskripsi) VALUES (%s, %s, %s)"
            val = (id, name, diskripsi)
            cursor.execute(sql, val)
            mydb.commit()
            self.label_3.setText("Data Kategori Berhasil Dimasukkan!")
            self.lineEdit_id.setText("")
            self.lineEdit_nama.setText("")
            self.lineEdit_diskripsi.setText("")
        except mc.Error as e:
            error_message = f"Error: {e}"
            self.label_3.setText(error_message)

    def updateSatuan(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "penjualan"
            )
            cursor = mydb.cursor()
            id = self.lineEdit_id.text()
            name = self.lineEdit_nama.text()
            diskripsi = self.lineEdit_diskripsi.text()

            sql = "UPDATE satuan SET name = %s, diskripsi = %s WHERE id = %s"
            val = (name, diskripsi, id)
            cursor.execute(sql, val)
            mydb.commit()
            self.label_3.setText("Data Satuan Berhasil Diubah!")
            self.lineEdit_id.setText("")
            self.lineEdit_nama.setText("")
            self.loadSatuan()
        except mc.Error as e:
            error_message = f"Error: {e}"
            self.label_3.setText(error_message)


    def deleteSatuan(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "penjualan"
            )
            cursor = mydb.cursor()
            id = self.lineEdit_id.text()
            name = self.lineEdit_nama.text()
            diskripsi = self.lineEdit_diskripsi.text()

            sql = "DELETE FROM satuan WHERE id = %s AND name =%s AND diskripsi =%s"
            val = (id, name, diskripsi)
            cursor.execute(sql, val)
            mydb.commit()
            self.label_3.setText("Data Kategori Berhasil Dihapus!")
            self.lineEdit_id.setText("")
            self.lineEdit_nama.setText("")
            self.lineEdit_diskripsi.setText("")
        except mc.Error as e:
            error_message = f"Error: {e}"
            self.label_3.setText(error_message)


    def loadSatuan(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "penjualan"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM satuan ORDER BY id ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                    self.label_3.setText("Data Satuan Berhasil Ditampilkan!")
        except mc.Error as err:
            self.label_3.setText("Data Satuan Gagal Ditampilkan!")

    def cariData(self):
        try:
            keyword = self.lineEdit_3.text()
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="penjualan"
            )
            cursor = mydb.cursor()
            sql = "SELECT * FROM satuan WHERE id LIKE %s OR name LIKE %s OR diskripsi LIKE %s"
            val = ("%{}%".format(keyword), "%{}%".format(keyword), "%{}%".format(keyword))
            cursor.execute(sql, val)
            result = cursor.fetchall()
        
            if not result:
                self.label_3.setText("Data Satuan Yang Dicari Tidak Ada")
                self.tableWidget.setRowCount(0)
                return

            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        
            self.label_3.setText("Data Satuan Yang Dicari Ditampilkan")
        except mc.Error as e:
            self.label_3.setText(f"Terjadi Kesalahan Saat Mencari Data: {e}")

    def retranslateUi(self, FormSatuan):
        _translate = QtCore.QCoreApplication.translate
        FormSatuan.setWindowTitle(_translate("FormSatuan", "Form"))
        self.label.setText(_translate("FormSatuan", "ID Satuan"))
        self.label_2.setText(_translate("FormSatuan", "Nama Satuan"))
        self.label_4.setText(_translate("FormSatuan", "Deskripsi"))
        self.pushButton.setText(_translate("FormSatuan", "INSERT"))
        self.pushButton_2.setText(_translate("FormSatuan", "UPDATE"))
        self.pushButton_3.setText(_translate("FormSatuan", "DELETE"))
        self.pushButton_4.setText(_translate("FormSatuan", "LOAD DATA"))
        self.label_3.setText(_translate("FormSatuan", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormSatuan", "No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormSatuan", "Nama Satuan"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormSatuan", "Deskripsi"))
        self.pushButton_5.setText(_translate("FormSatuan", "SEARCHING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSatuan = QtWidgets.QWidget()
    ui = Ui_FormSatuan()
    ui.setupUi(FormSatuan)
    FormSatuan.show()
    sys.exit(app.exec_())
