# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userfull.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector as mc
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_FormUser(object):
    def setupUi(self, FormUser):
        FormUser.setObjectName("FormUser")
        FormUser.resize(566, 725)
        self.verticalLayoutWidget = QtWidgets.QWidget(FormUser)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(FormUser)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 10, 281, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_id = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout_2.addWidget(self.lineEdit_id)
        self.lineEdit_nik = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_nik.setObjectName("lineEdit_nik")
        self.verticalLayout_2.addWidget(self.lineEdit_nik)
        self.lineEdit_username = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_2.addWidget(self.lineEdit_username)
        self.lineEdit_fullname = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_fullname.setObjectName("lineEdit_fullname")
        self.verticalLayout_2.addWidget(self.lineEdit_fullname)
        self.lineEdit_password = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.lineEdit_role = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_role.setObjectName("lineEdit_role")
        self.verticalLayout_2.addWidget(self.lineEdit_role)
        self.lineEdit_email = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout_2.addWidget(self.lineEdit_email)
        self.lineEdit_telp = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_telp.setObjectName("lineEdit_telp")
        self.verticalLayout_2.addWidget(self.lineEdit_telp)
        self.lineEdit_alamat = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.verticalLayout_2.addWidget(self.lineEdit_alamat)
        self.lineEdit_isactive = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_isactive.setObjectName("lineEdit_isactive")
        self.verticalLayout_2.addWidget(self.lineEdit_isactive)
        self.horizontalLayoutWidget = QtWidgets.QWidget(FormUser)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 340, 461, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        self.pushButton.clicked.connect(self.insertUser)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        self.pushButton_2.clicked.connect(self.updateUser)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        self.pushButton_3.clicked.connect(self.deleteUser)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        self.pushButton_4.clicked.connect(self.loadUser)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.label_3 = QtWidgets.QLabel(FormUser)
        self.label_3.setGeometry(QtCore.QRect(20, 410, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(FormUser)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 460, 461, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.cellClicked.connect(self.cellClick)

        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(FormUser)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 660, 461, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_3.textChanged.connect(self.cariData)

        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)

        self.pushButton_5.clicked.connect(self.cariData)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)

        self.retranslateUi(FormUser)
        QtCore.QMetaObject.connectSlotsByName(FormUser)

    def cellClick(self, row, column):
        try:
            id = self.tableWidget.item(row, 0).text()
            nik = self.tableWidget.item(row, 1).text()
            username = self.tableWidget.item(row, 2).text()
            full_name = self.tableWidget.item(row, 3).text()
            password = self.tableWidget.item(row, 4).text()
            role = self.tableWidget.item(row, 5).text()
            email = self.tableWidget.item(row, 6).text()
            telp = self.tableWidget.item(row, 7).text()
            alamat = self.tableWidget.item(row, 8).text()
            is_active = self.tableWidget.item(row, 9).text()

            self.lineEdit_id.setText(id)
            self.lineEdit_nik.setText(nik)
            self.lineEdit_username.setText(username)
            self.lineEdit_fullname.setText(full_name)
            self.lineEdit_password.setText(password)
            self.lineEdit_role.setText(role)
            self.lineEdit_email.setText(email)
            self.lineEdit_telp.setText(telp)
            self.lineEdit_alamat.setText(alamat)
            self.lineEdit_isactive.setText(is_active)

        except Exception as e:
            error_message = f"Error: {e}"
            self.label_3.setText(error_message)

    def insertUser(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "penjualan"
            )
            cursor = mydb.cursor()
            id = self.lineEdit_id.text()
            nik = self.lineEdit_nik.text()
            username = self.lineEdit_username.text()
            full_name = self.lineEdit_fullname.text()
            password = self.lineEdit_password.text()
            role = self.lineEdit_role.text()
            email = self.lineEdit_email.text()
            telp = self.lineEdit_telp.text()
            alamat = self.lineEdit_alamat.text()
            is_active = self.lineEdit_isactive.text()

            sql = "INSERT INTO user (id, nik, username, full_name, password, role, email, telp, alamat, is_active) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
            val = (id, nik, username, full_name, password, role, email, telp, alamat, is_active)
            cursor.execute(sql, val)
            mydb.commit()
            self.label_3.setText("Data User Berhasil Dimasukkan!")
            self.lineEdit_id.setText("")
            self.lineEdit_nik.setText("")
            self.lineEdit_username.setText("")
            self.lineEdit_fullname.setText("")
            self.lineEdit_password.setText("")
            self.lineEdit_role.setText("")
            self.lineEdit_email.setText("")
            self.lineEdit_telp.setText("")
            self.lineEdit_alamat.setText("")
            self.lineEdit_isactive.setText("")
        except mc.Error as e:
            error_message = f"Error: {e}"
            self.label_3.setText(error_message)

    def updateUser(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "penjualan"
            )
            cursor = mydb.cursor()
            id = self.lineEdit_id.text()
            nik = self.lineEdit_nik.text()
            username = self.lineEdit_username.text()
            full_name = self.lineEdit_fullname.text()
            password = self.lineEdit_password.text()
            role = self.lineEdit_role.text()
            email = self.lineEdit_email.text()
            telp = self.lineEdit_telp.text()
            alamat = self.lineEdit_alamat.text()
            is_active = self.lineEdit_isactive.text()

            sql = "UPDATE user SET nik = %s, username = %s, full_name = %s, password = %s, role = %s, email = %s, telp = %s, alamat = %s, is_active = %s WHERE id = %s"
            val = (nik, username, full_name, password, role, email, telp, alamat, is_active, id)
            cursor.execute(sql, val)
            mydb.commit()
            self.label_3.setText("Data User Berhasil Diubah!")
            self.lineEdit_id.setText("")
            self.lineEdit_nik.setText("")
            self.lineEdit_username.setText("")
            self.lineEdit_fullname.setText("")
            self.lineEdit_password.setText("")
            self.lineEdit_role.setText("")
            self.lineEdit_email.setText("")
            self.lineEdit_telp.setText("")
            self.lineEdit_alamat.setText("")
            self.lineEdit_isactive.setText("")
            self.loadUser()
        except mc.Error as e:
            error_message = f"Error: {e}"
            self.label_3.setText(error_message)


    def deleteUser(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "penjualan"
            )
            cursor = mydb.cursor()
            id = self.lineEdit_id.text()
            nik = self.lineEdit_nik.text()
            username = self.lineEdit_username.text()
            full_name = self.lineEdit_fullname.text()
            password = self.lineEdit_password.text()
            role = self.lineEdit_role.text()
            email = self.lineEdit_email.text()
            telp = self.lineEdit_telp.text()
            alamat = self.lineEdit_alamat.text()
            is_active = self.lineEdit_isactive.text()

            sql = "DELETE FROM user WHERE id = %s AND nik =%s AND username =%s AND full_name=%s AND password = %s AND role = %s AND email = %s AND telp = %s AND alamat = %s AND is_active = %s"
            val = (id, nik, username, full_name, password, role, email, telp, alamat, is_active)
            cursor.execute(sql, val)
            mydb.commit()
            self.label_3.setText("Data User Berhasil Dihapus!")
            self.lineEdit_id.setText("")
            self.lineEdit_nik.setText("")
            self.lineEdit_username.setText("")
            self.lineEdit_fullname.setText("")
            self.lineEdit_password.setText("")
            self.lineEdit_role.setText("")
            self.lineEdit_email.setText("")
            self.lineEdit_telp.setText("")
            self.lineEdit_alamat.setText("")
            self.lineEdit_isactive.setText("")
        except mc.Error as e:
            error_message = f"Error: {e}"
            self.label_3.setText(error_message)


    def loadUser(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "penjualan"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM user ORDER BY id ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                    self.label_3.setText("Data User Berhasil Ditampilkan!")
        except mc.Error as err:
            self.label_3.setText("Data User Gagal Ditampilkan!")

    def cariData(self):
        try:
            keyword = self.lineEdit_3.text()
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="penjualan"
            )
            cursor = mydb.cursor()
            sql = "SELECT * FROM user WHERE id LIKE %s OR nik LIKE %s OR username LIKE %s OR full_name LIKE %s OR password LIKE %s OR role LIKE %s OR phone LIKE %s OR email LIKE %s OR alamat LIKE %s OR last_login LIKE %s%s OR is_active LIKE %s"
            val = ("%{}%".format(keyword), "%{}%".format(keyword), "%{}%".format(keyword),  "%{}%".format(keyword),  "%{}%".format(keyword),  "%{}%".format(keyword),  "%{}%".format(keyword),  "%{}%".format(keyword),  "%{}%".format(keyword),  "%{}%".format(keyword), "%{}%".format(keyword))
            cursor.execute(sql, val)
            result = cursor.fetchall()
        
            if not result:
                self.label_3.setText("Data User Yang Dicari Tidak Ada")
                self.tableWidget.setRowCount(0)
                return

            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        
            self.label_3.setText("Data User Yang Dicari Ditampilkan")
        except mc.Error as e:
            self.label_3.setText(f"Terjadi Kesalahan Saat Mencari Data: {e}")

    def retranslateUi(self, FormUser):
        _translate = QtCore.QCoreApplication.translate
        FormUser.setWindowTitle(_translate("FormUser", "Form"))
        self.label.setText(_translate("FormUser", "ID User"))
        self.label_2.setText(_translate("FormUser", "NIK"))
        self.label_4.setText(_translate("FormUser", "Username"))
        self.label_6.setText(_translate("FormUser", "Full Name"))
        self.label_5.setText(_translate("FormUser", "Password"))
        self.label_7.setText(_translate("FormUser", "Role"))
        self.label_8.setText(_translate("FormUser", "Email"))
        self.label_9.setText(_translate("FormUser", "Telpon"))
        self.label_10.setText(_translate("FormUser", "Alamat"))
        self.label_11.setText(_translate("FormUser", "Is Active"))
        self.pushButton.setText(_translate("FormUser", "INSERT"))
        self.pushButton_2.setText(_translate("FormUser", "UPDATE"))
        self.pushButton_3.setText(_translate("FormUser", "DELETE"))
        self.pushButton_4.setText(_translate("FormUser", "LOAD DATA"))
        self.label_3.setText(_translate("FormUser", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormUser", "No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormUser", "NIK"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormUser", "Username"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FormUser", "Full Name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FormUser", "Password"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FormUser", "Role"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("FormUser", "Email"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("FormUser", "Telpon"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("FormUser", "Alamat"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("FormUser", "Is_Active"))
        self.pushButton_5.setText(_translate("FormUser", "SEARCHING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormUser = QtWidgets.QWidget()
    ui = Ui_FormUser()
    ui.setupUi(FormUser)
    FormUser.show()
    sys.exit(app.exec_())
